[phases.setup]
nixPkgs = ["...", "nodejs-18_x"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd client && npm install"
]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000}"
